### ISSUE TITLE
bustimes broken in magic mirror 2.13

### ISSUE THREAD

**Issue by herwarth** [73cirdan/MMM-bustimes#10]
The modules shows:

Geen mogelijkheden

Config:
                {
                        module: "bustimes",
                        position: "bottom_left",
                        header: "Vertrektijden",
                        config: {
                                timepointcode: "31008713,31008714",
                                displaymode: "large",
                                showDestination: true,
                                departs: 8
                        }
                },

**Comment by 73cirdan** [comment]
just tried http://v0.ovapi.nl/tpc/31008713 in the browser and i get a good response. Still having problems herwarth?
 I can check in the next days how this tpc works in my mirror.

**Comment by 73cirdan** [comment]
Did check it today, and it works fine. Geen mogelijkheden indicates that there are no times available for the tpc's used. I guess the line does not have a frequent operating window?
