### ISSUE TITLE
after switch to axios: TypeError: Cannot read properties of undefined (reading 'get') 

### ISSUE THREAD

**Issue by scientific-method-course** [73cirdan/MMM-bustimes#15]
I just updated to the current version of MMM-bustimes, where the main change seems to be the switch to axios.
This lead the the error TypeError: Cannot read properties of undefined (reading 'get') 

The error seems to be related to the issue quoted here: 
https://forum.magicmirror.builders/topic/13639/axios-request-returns-no-data-while-http-request-does/5

What seemed to solve the problem was to add a line to the first two lines in node_helper.js:

const NodeHelper = require('node_helper');
const axios = require('axios').default;
axios.defaults.headers.common['User-Agent'] = 'PostmanRuntime/7.26.2';

Best, Arnold

**Comment by 73cirdan** [comment]
same solution as mmm-rainfc. confirmed over there by user [scientific-method-course](https://github.com/scientific-method-course)
