### ISSUE TITLE
Nothing displayed

### ISSUE THREAD

**Issue by bajosoto** [73cirdan/MMM-bustimes#2]
Hi,
I added the module and followed all steps, but I don't see anything displayed by the module. I also tried using the default config, I tried moving it to different positions, but no luck.

The module helper seems to be working fine and the socket is connecting.
```
Initializing new module helper ...
Module helper loaded: MMM-bustimes
Connecting socket for: MMM-bustimes
Sockets connected & modules started ...
```

Is there any way I can debug where the problem is?

**Comment by 73cirdan** [comment]
You could uncomment line 121 in the bustimes.js, restart mm, then look in the browser console and check if the line display log info. The are more commented log statement you could uncomment, see if that helps, let me know how you progress. Browser console: (ctrl shift i) while the mm screen shows

**Comment by 73cirdan** [comment]
no follow up -> closing
