### ISSUE TITLE
Tpc

### ISSUE THREAD

**Issue by jurgverhoeven** [73cirdan/MMM-bustimes#5]
If I want to use this busline: “http://v0.ovapi.nl/line/ARR_22091_1”. How do I find the TPC?

**Comment by 73cirdan** [comment]
In the example url from the readme: http://v0.ovapi.nl/line/ARR_28167_2 during the day there is an actuals part. In this part you find an timingpointcode. E.g

{"ARR_28167_2":{"Line":{"LineWheelchairAccessible":"NOTACCESSIBLE","TransportType":"BUS","DestinationName50":"Stiens Langebuorren","DataOwnerCode":"ARR","DestinationCode":"2715","LinePublicNumber":"7911","LinePlanningNumber":"28167","LineName":"Stiens, Langebuorren - Alde Leie, Brug","LineDirection":2},"Actuals":{"ARR_20180922_28167_6034_0":{"IsTimingStop":true,"DestinationName50":"Stiens Langebuorren","DataOwnerCode":"ARR","OperatorCode":"ARR","FortifyOrderNumber":0,"TransportType":"BUS","Latitude":47.974766,"Longitude":3.3135424,"JourneyNumber":6034,"JourneyPatternCode":2129494546,"LocalServiceLevelCode":20180922,"LineDirection":2,"OperationDate":"2018-09-22","TimingPointCode":"20320110","WheelChairAccessible":"NOTACCESSIBLE","LineName":"Stiens, Langebuorren - Alde Leie, Brug","LinePublicNumber":"7911","LastUpdateTimeStamp":"2018-09-21T18:27:00+0200","DestinationCode":"2715","ExpectedDepartureTime":"2018-09-22T15:45:00","UserStopOrderNumber":1,"ProductFormulaType":"2","TimingPointName":"Brug","LinePlanningNumber":"28167","StopAreaCode":"OliBru","TimingPointDataOwnerCode":"ALGEMEEN","TimingPointTown":"Alde Leie","TripStopStatus":"PLANNED","UserStopCode":"20320110","JourneyStopType":"FIRST","TargetArrivalTime":"2018-09-22T15:45:00","TargetDepartureTime":"2018-09-22T15:45:00","ExpectedArrivalTime":"2018-09-22T15:45:00","TimingPointWheelChairAccessible":"ACCESSIBLE","TimingPointVisualAccessible":"ACCESSIBLE"}},"ServerTime":"2018-09-22T12:52:05Z","Network":{"2129494546":{"1":{"Longitude":3.3135424,"Latitude":47.974766,"TimingPointTown":"Alde Leie","TimingPointName":"Brug","TimingPointCode":"20320110","StopAreaCode":"OliBru","TimingPointWheelChairAccessible":"NOTACCESSIBLE","TimingPointVisualAccessible":"ACCESSIBLE","IsTimingStop":true,"UserStopOrderNumber":1},"2":{"Longitude":3.3135424,"Latitude":47.974766,"TimingPointTown":"Stiens","TimingPointName":"Langebuorren","TimingPointCode":"20141210","StopAreaCode":"StiLan","TimingPointWheelChairAccessible":"NOTACCESSIBLE","TimingPointVisualAccessible":"NOTACCESSIBLE","IsTimingStop":true,"UserStopOrderNumber":2}}}}}


But in your line there is an empty actuals part.  😕

**Comment by 73cirdan** [comment]
Ah. I see. The line does not operate in the weekend. Try asking for the line url during a time the bus actually drives. Then the acuals part should be there...

**Comment by 73cirdan** [comment]
no follow up for 2 weeks, assume this can be closed
