### ISSUE TITLE
Posibility to order based on timingPointCode

### ISSUE THREAD

**Issue by unreal4u** [73cirdan/MMM-bustimes#8]
Hi!

I live in a small town so I have set up 3 starting points, one in the town itself (Hoogeloon), another one in the next town (Hapert) and another one in another neighbour town (Eersel). However, currently it orders them in the main view in (I assume) alphabetic order as Eersel, Hapert and Hoogeloon and I would like to order them based on their importance.

This is my current configuration: 

```
    {
      module: "bustimes",
      position: "top_right",
      header: "Bustijden",
      config: {
        timingPointCode: "64440310,64510160,64310020",
        displaymode: "large",
        showTownName: false,
        departs: 3,
        showDelay: true
      }
    },
```

Would it be possible to order them based on the position of the timingPointCode or any other way?

Thanks in advance for this plugin, it is truly useful for me!

Greetings.

PD: If you are testing this, due to the coronavirus we have no busses going out from our town, so don't be too surprised if you don't see any traffic :)

**Comment by 73cirdan** [comment]
I will look into this

**Comment by 73cirdan** [comment]
Took some time ;-)
looked in before but could no find a good solution, but thought of something

you could run the module multiple times. If you remove the header for the 2nd an 3rd instance it looks ok ?

   ```
 {
        module: "MMM-bustimes",
        position: "top_left",
        header: "Bustimes",
        config: {
            timingPointCode: "64440310", //  Hoogeloon
            displaymode: "large",
            showTownName: false,
            departures: 3,
            showDelay: true
        }
    },
    {
        module: "MMM-bustimes",
        position: "top_left",
        config: {
            timingPointCode: "64510160", //  Hapert
            displaymode: "large",
            showTownName: false,
            departures: 3,
            showDelay: true
        }
    },
    {
        module: "MMM-bustimes",
        position: "top_left",
        config: {
            timingPointCode: "64310020", //   Eeersel
            displaymode: "large",
            showTownName: false,
            departures: 3,
            showDelay: true
        }
    },
```

**Comment by 73cirdan** [comment]
alternative is to hide stop name and use the 3 headers for the stop name

 ```
   {
        module: "MMM-bustimes",
        position: "top_left",
        header: "Bus Hoogeloon",
        config: {
            timingPointCode: "64440310", //  Hoogeloon
            displaymode: "large",
            showTownName: false,
            departures: 3,
            showDelay: true,
            alwaysShowStopName: false,
        }
    },
    {
        module: "MMM-bustimes",
        position: "top_left",
        header: "Bus Hapert",
        config: {
            timingPointCode: "64510160", //  Hapert
            displaymode: "large",
            showTownName: false,
            departures: 3,
            showDelay: true,
            alwaysShowStopName: false,
        }
    },
    {
        module: "MMM-bustimes",
        position: "top_left",
        header: "Bus Eersel",
        config: {
            timingPointCode: "64310020", //   Eeersel
            displaymode: "large",
            showTownName: false,
            departures: 3,
            showDelay: true,
            alwaysShowStopName: false,
        }
    },

```

**Comment by 73cirdan** [comment]
Change the order in the config file to change the order on screen

**Comment by unreal4u** [comment]
Sadly the monitor I was using for my magic mirror decided to begin smoking one day hahaha so I haven't been using magicmirror for some time :( 

But as soon as somebody donates me a new monitor I will be following your advise, so thanks! I've at least edited my configuration file so when it's time to set it up again, I will already have it available, this should work as well so thanks man, great job!
